### ISSUE TITLE
Online version not loading correctly?

### ISSUE THREAD

**Issue by Liquidream** [Willy-JL/SmoothieVid#1]
Hi, 
I'm really interested in trying out this project, but alas, the [online version](https://smoothievid.willyjl.dev/) does not appear to be working correctly? (for me, anyway)

I'm just seeing this...

![image](https://github.com/Willy-JL/SmoothieVid/assets/2211678/3afd38e4-ff6a-4b16-8b9c-1609c0a8d79e)

**Comment by WillyJL** [comment]
My server hosting has been acting up and dying randomly, am yet to find out why. It was never that reliable to begin with, but it's been dying every couple hours for the past few days

**Comment by WillyJL** [comment]
@Liquidream finally migrated smoothievid and personal website to a more stable provider, should be good now. also ill be looking into serving ffmpeg.wasm-core locally, since i see that unpkg is starting to be quite slow, while i could just serve it statically and fully cache with cloudflare

**Comment by WillyJL** [comment]
also we have https://smoothievid.app/ now! the old https://smoothievid.willyjl.dev/ is still available as a CNAME record however
